# Generated by Django 3.0.7 on 2021-03-10 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('lat', models.FloatField(max_length=20, verbose_name='Ширина')),
                ('lon', models.FloatField(max_length=20, verbose_name='Долгота')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
