# Generated by Django 3.0.7 on 2021-04-26 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Необработанный', 'необработанный'), ('Обработанный', 'обработанный')], db_index=True, default='необработанный', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Наличностью', 'наличностью'), ('Электронно', 'электронно')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='place',
            name='time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру'),
        ),
    ]
