# Generated by Django 3.0.7 on 2021-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20210609_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Необработанный', 'необработанный'), ('Обработанный', 'обработанный')], db_index=True, default='Необработанный', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
