# Generated by Django 3.0.7 on 2021-04-26 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(max_length=20, verbose_name='Ширина')),
                ('lon', models.FloatField(max_length=20, verbose_name='Долгота')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
