# Generated by Django 3.0.7 on 2021-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
