# Generated by Django 3.0.7 on 2021-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20210227_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Наличностью', 'наличностью'), ('Электронно', 'электронно')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
