# Generated by Django 3.0.7 on 2021-04-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20210426_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
